import { PATTERN_EMAIL, PATTERN_PASSWORD, PATTERN_PHONE } from './pattern.ts'

const REGEX_EMAIL = new RegExp(PATTERN_EMAIL)
const REGEX_PASSWORD = new RegExp(PATTERN_PASSWORD)
const REGEX_PHONE = new RegExp(PATTERN_PHONE)

export { REGEX_EMAIL, REGEX_PASSWORD, REGEX_PHONE }
